/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gui;

import Conexion.Conexion;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Personal
 */
public class Frm_BuscadorCliente extends javax.swing.JFrame {

    /**
     * Creates new form Frm_BuscadorCliente
     */
    public Frm_BuscadorCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbg_Filtro = new javax.swing.ButtonGroup();
        jl_Filtro = new javax.swing.JLabel();
        jrb_Documento = new javax.swing.JRadioButton();
        jrb_Nombre = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jta_Cliente = new javax.swing.JTable();
        jb_Buscar = new javax.swing.JButton();
        jt_Filtro = new javax.swing.JTextField();
        jb_Agregar = new javax.swing.JButton();
        jl_Documento = new javax.swing.JLabel();
        jl_Nombre = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jl_Filtro.setText("Filtro");

        jbg_Filtro.add(jrb_Documento);
        jrb_Documento.setSelected(true);
        jrb_Documento.setText("Documento");
        jrb_Documento.setToolTipText("Filtrar por documento");
        jrb_Documento.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jrb_DocumentoItemStateChanged(evt);
            }
        });

        jbg_Filtro.add(jrb_Nombre);
        jrb_Nombre.setText("Nombre");
        jrb_Nombre.setToolTipText("Filtrar por nombre");
        jrb_Nombre.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jrb_NombreItemStateChanged(evt);
            }
        });

        jta_Cliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Documento", "Nombre"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jta_Cliente.getTableHeader().setResizingAllowed(false);
        jta_Cliente.getTableHeader().setReorderingAllowed(false);
        jta_Cliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jta_ClienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jta_Cliente);
        if (jta_Cliente.getColumnModel().getColumnCount() > 0) {
            jta_Cliente.getColumnModel().getColumn(0).setPreferredWidth(120);
            jta_Cliente.getColumnModel().getColumn(1).setPreferredWidth(400);
        }

        jb_Buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/img_buscar.png"))); // NOI18N
        jb_Buscar.setText("Buscar");
        jb_Buscar.setToolTipText("Buscar");
        jb_Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_BuscarActionPerformed(evt);
            }
        });

        jt_Filtro.setToolTipText("<html>\nDigite el valor por el cual desea filtrar los clientes\n<p>\nDeje en blanco si desea ver todos los clientes\n</html>");
        jt_Filtro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jt_FiltroKeyTyped(evt);
            }
        });

        jb_Agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/img_nuevo.png"))); // NOI18N
        jb_Agregar.setText("Agregar");
        jb_Agregar.setToolTipText("Haga clic para agregar el cliente seleccionado");
        jb_Agregar.setEnabled(false);
        jb_Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_AgregarActionPerformed(evt);
            }
        });

        jl_Documento.setText("Documento");

        jl_Nombre.setText("Nombre");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jl_Filtro)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jrb_Documento)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jrb_Nombre)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jt_Filtro, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jb_Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jl_Nombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jl_Documento, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jb_Agregar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_Filtro)
                    .addComponent(jrb_Documento)
                    .addComponent(jrb_Nombre)
                    .addComponent(jb_Buscar)
                    .addComponent(jt_Filtro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jl_Documento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jl_Nombre)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jb_Agregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jrb_DocumentoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jrb_DocumentoItemStateChanged
        jt_Filtro.setText("");
    }//GEN-LAST:event_jrb_DocumentoItemStateChanged

    private void jrb_NombreItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jrb_NombreItemStateChanged
        jt_Filtro.setText("");
    }//GEN-LAST:event_jrb_NombreItemStateChanged

    private void jta_ClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jta_ClienteMouseClicked
        // rowToFields(jta_Cliente.getSelectedRow());
        int fila = jta_Cliente.getSelectedRow();
        if(fila!=-1){
            jb_Agregar.setEnabled(true);
            jl_Documento.setText(jta_Cliente.getValueAt(fila, 0).toString());
            jl_Nombre.setText(jta_Cliente.getValueAt(fila, 1).toString());
        }else
            jb_Agregar.setEnabled(false);
    }//GEN-LAST:event_jta_ClienteMouseClicked

    private void jb_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_BuscarActionPerformed
        llenarTablaCliente();
    }//GEN-LAST:event_jb_BuscarActionPerformed

    private void jt_FiltroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jt_FiltroKeyTyped
        if (jrb_Documento.isSelected() && !Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }
        llenarTablaCliente();
    }//GEN-LAST:event_jt_FiltroKeyTyped

    private void jb_AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_AgregarActionPerformed
       JIF_Factura.jt_CodigoCliente.setText(jl_Documento.getText());
       JIF_Factura.jl_NomCliente.setText(jl_Nombre.getText());
       this.dispose();
    }//GEN-LAST:event_jb_AgregarActionPerformed

    private void llenarTablaCliente(){
        DefaultTableModel dtm = (DefaultTableModel) jta_Cliente.getModel();
        while (dtm.getRowCount() > 0) {
            dtm.removeRow(0);
        }
        jta_Cliente.setModel(dtm);
        try {
            Conexion c = new Conexion();
            Statement s = c.c.createStatement();
            String tipoFiltro = (jrb_Documento.isSelected()) ? "Documento" : "Nombre";
            String valorFiltro = jt_Filtro.getText();
            String sentence = "CALL sp_BuscadorCliente(\"" + tipoFiltro
                    + "\",\"" + valorFiltro + "\")";
            ResultSet r = s.executeQuery(sentence);
            while (r.next()) {
                Object[] o = new Object[]{r.getString(1), r.getString(2)};
                dtm.addRow(o);
                jta_Cliente.setModel(dtm);
            }
            c.c.close();
        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_BuscadorCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_BuscadorCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_BuscadorCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_BuscadorCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_BuscadorCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jb_Agregar;
    private javax.swing.JButton jb_Buscar;
    private javax.swing.ButtonGroup jbg_Filtro;
    private javax.swing.JLabel jl_Documento;
    private javax.swing.JLabel jl_Filtro;
    private javax.swing.JLabel jl_Nombre;
    private javax.swing.JRadioButton jrb_Documento;
    private javax.swing.JRadioButton jrb_Nombre;
    private javax.swing.JTextField jt_Filtro;
    private javax.swing.JTable jta_Cliente;
    // End of variables declaration//GEN-END:variables
}
