/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gui;

import Conexion.Conexion;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author DiegoAndrés
 */
public class JIF_Proveedor extends javax.swing.JInternalFrame {

    /**
     * Creates new form JIF_Proveedor
     */
    public JIF_Proveedor() {
        initComponents();
        setTitle("PROVEEDOR");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jl_iNombre = new javax.swing.JLabel();
        jl_Pais = new javax.swing.JLabel();
        jl_Ciudad = new javax.swing.JLabel();
        jl_Direccion = new javax.swing.JLabel();
        jl_Telefono = new javax.swing.JLabel();
        jl_Correo_Electronico = new javax.swing.JLabel();
        jl_Web = new javax.swing.JLabel();
        jt_Nombre = new javax.swing.JTextField();
        jt_Pais = new javax.swing.JTextField();
        jt_Ciudad = new javax.swing.JTextField();
        jt_Direccion = new javax.swing.JTextField();
        jt_Telefono = new javax.swing.JTextField();
        jt_Correo_Electronico = new javax.swing.JTextField();
        jt_Web = new javax.swing.JTextField();
        jb_Agregar = new javax.swing.JButton();
        jb_Modificar = new javax.swing.JButton();
        jl_idProveedor = new javax.swing.JLabel();
        jt_idProveedor = new javax.swing.JTextField();
        jl_Icono = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("PROVEEDOR");
        setPreferredSize(new java.awt.Dimension(1020, 718));
        setVisible(true);
        getContentPane().setLayout(null);

        jl_iNombre.setText("Nombre:");
        getContentPane().add(jl_iNombre);
        jl_iNombre.setBounds(70, 100, 92, 23);

        jl_Pais.setText("País:");
        getContentPane().add(jl_Pais);
        jl_Pais.setBounds(70, 130, 92, 23);

        jl_Ciudad.setText("Ciudad:");
        getContentPane().add(jl_Ciudad);
        jl_Ciudad.setBounds(70, 160, 92, 23);

        jl_Direccion.setText("Dirección:");
        getContentPane().add(jl_Direccion);
        jl_Direccion.setBounds(70, 190, 92, 23);

        jl_Telefono.setText("Teléfono:");
        getContentPane().add(jl_Telefono);
        jl_Telefono.setBounds(70, 220, 92, 23);

        jl_Correo_Electronico.setText("Correo Electrónico:");
        getContentPane().add(jl_Correo_Electronico);
        jl_Correo_Electronico.setBounds(70, 250, 110, 23);

        jl_Web.setText("Página Web:");
        getContentPane().add(jl_Web);
        jl_Web.setBounds(70, 280, 92, 23);

        jt_Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt_NombreActionPerformed(evt);
            }
        });
        jt_Nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jt_NombreKeyTyped(evt);
            }
        });
        getContentPane().add(jt_Nombre);
        jt_Nombre.setBounds(180, 100, 320, 25);

        jt_Pais.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jt_PaisKeyTyped(evt);
            }
        });
        getContentPane().add(jt_Pais);
        jt_Pais.setBounds(180, 130, 320, 25);

        jt_Ciudad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jt_CiudadKeyTyped(evt);
            }
        });
        getContentPane().add(jt_Ciudad);
        jt_Ciudad.setBounds(180, 160, 320, 25);

        jt_Direccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jt_DireccionKeyTyped(evt);
            }
        });
        getContentPane().add(jt_Direccion);
        jt_Direccion.setBounds(180, 190, 320, 25);

        jt_Telefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jt_TelefonoKeyTyped(evt);
            }
        });
        getContentPane().add(jt_Telefono);
        jt_Telefono.setBounds(180, 220, 320, 25);

        jt_Correo_Electronico.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jt_Correo_ElectronicoKeyTyped(evt);
            }
        });
        getContentPane().add(jt_Correo_Electronico);
        jt_Correo_Electronico.setBounds(180, 250, 320, 25);

        jt_Web.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jt_WebKeyTyped(evt);
            }
        });
        getContentPane().add(jt_Web);
        jt_Web.setBounds(180, 280, 320, 25);

        jb_Agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/img_nuevo.png"))); // NOI18N
        jb_Agregar.setText("Agregar");
        jb_Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_AgregarActionPerformed(evt);
            }
        });
        getContentPane().add(jb_Agregar);
        jb_Agregar.setBounds(150, 340, 114, 30);

        jb_Modificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/modificar.png"))); // NOI18N
        jb_Modificar.setText("Modificar");
        jb_Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_ModificarActionPerformed(evt);
            }
        });
        getContentPane().add(jb_Modificar);
        jb_Modificar.setBounds(290, 340, 114, 30);

        jl_idProveedor.setText("Id. Proveedor:");
        getContentPane().add(jl_idProveedor);
        jl_idProveedor.setBounds(70, 70, 92, 23);

        jt_idProveedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jt_idProveedorKeyTyped(evt);
            }
        });
        getContentPane().add(jt_idProveedor);
        jt_idProveedor.setBounds(180, 70, 320, 25);

        jl_Icono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/suppliers.jpg"))); // NOI18N
        getContentPane().add(jl_Icono);
        jl_Icono.setBounds(530, 50, 300, 280);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        getContentPane().add(jPanel1);
        jPanel1.setBounds(50, 50, 470, 280);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/fondo-blanco.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1020, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_AgregarActionPerformed
        if (evt.getSource() == jb_Agregar) {
            String id = jt_idProveedor.getText();
            String nombre = jt_Nombre.getText();
            String pais = jt_Pais.getText();
            String ciudad = jt_Ciudad.getText();
            String direccion = jt_Direccion.getText();
            String telefono = jt_Telefono.getText();
            String correo = jt_Correo_Electronico.getText();
            String web = jt_Web.getText();
            int ntelefono = Integer.parseInt(telefono);
            
            Conexion c;
            try { 
                    c = new Conexion();
                    try (Statement s = c.c.createStatement()) {
                        if (pais.equals("") || ciudad.equals("")){
                            pais = "Colombia";
                            ciudad = "Bogotá";                          
                        }
                    s.executeUpdate("insert into tb_Contacto (nombre, pais, ciudad, direccion, telefono, correoElectronico) VALUES ('" + nombre + "','" + pais + "','" + ciudad + "','" + direccion + "'," + ntelefono + ",'" + correo + "')");
                    ResultSet r = s.executeQuery("SELECT MAX(idUbicacion) FROM tb_Contacto");
                    if (r.next()) {
                        String ubicacion = r.getString(1);
                        int nubicacion = Integer.parseInt(ubicacion);
                        s.executeUpdate("insert into tb_Proveedor (idProveedor, paginaWeb, contacto_idUbicacion) VALUES ('" + id + "','" + web + "'," + nubicacion + ")");
                    }
                    JOptionPane.showMessageDialog(null, "Proveedor Registrado Satisfactoriamente!");
                    jt_idProveedor.setText("");
                    jt_Nombre.setText("");
                    jt_Pais.setText("");
                    jt_Ciudad.setText("");
                    jt_Direccion.setText("");
                    jt_Telefono.setText("");
                    jt_Correo_Electronico.setText("");
                    jt_Web.setText("");
                    s.close();
                }

            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(JIF_Cliente.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jb_AgregarActionPerformed

    private void jt_NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt_NombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jt_NombreActionPerformed

    private void jb_ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_ModificarActionPerformed
        String id = jt_idProveedor.getText();
        String nombre = jt_Nombre.getText();
        String pais = jt_Pais.getText();
        String ciudad = jt_Ciudad.getText();
        String direccion = jt_Direccion.getText();
        String telefono = jt_Telefono.getText();
        String correo = jt_Correo_Electronico.getText();
        String web = jt_Web.getText();
        int ntelefono = Integer.parseInt(telefono);
        
        Conexion c;
            try { 
                    c = new Conexion();try (Statement s = c.c.createStatement()) {
                    
                    if (pais.equals("") || ciudad.equals("")){
                        pais = "Colombia";
                        ciudad = "Bogotá";                          
                    }
                    s.executeUpdate("update tb_Contacto, tb_Proveedor set nombre = '" + nombre + "', pais = '" + pais + "', ciudad = '" + ciudad + "', direccion = '" + direccion + "', telefono = " + ntelefono + ", correoElectronico = '" + correo + "' , paginaWeb = '" + web + "' " + "where tb_Contacto.idUbicacion = tb_Proveedor.contacto_idUbicacion and idProveedor = " + id);
                    JOptionPane.showMessageDialog(null, "Proveedor Modificado Satisfactoriamente!");
                    jt_idProveedor.setText("");
                    jt_Nombre.setText("");
                    jt_Pais.setText("");
                    jt_Ciudad.setText("");
                    jt_Direccion.setText("");
                    jt_Telefono.setText("");
                    jt_Correo_Electronico.setText("");
                    jt_Web.setText("");
                    s.close();
                }

            } catch (    ClassNotFoundException | SQLException ex) {
                Logger.getLogger(JIF_Cliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jb_ModificarActionPerformed

    private void jt_idProveedorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jt_idProveedorKeyTyped
        char caracter = evt.getKeyChar();
        if(((caracter < '0') || (caracter > '9')) && (caracter != '\b' /*corresponde a BACK_SPACE*/)) {
             evt.consume();  // ignorar el evento de teclado
        }
    }//GEN-LAST:event_jt_idProveedorKeyTyped

    private void jt_NombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jt_NombreKeyTyped
        int limite = 60;
        if (jt_Nombre.getText().length() >= limite){
            evt.consume();
        }
    }//GEN-LAST:event_jt_NombreKeyTyped

    private void jt_PaisKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jt_PaisKeyTyped
        int limite = 20;
        if (jt_Pais.getText().length() >= limite){
            evt.consume();
        }
    }//GEN-LAST:event_jt_PaisKeyTyped

    private void jt_CiudadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jt_CiudadKeyTyped
        int limite = 20;
        if (jt_Ciudad.getText().length() >= limite){
            evt.consume();
        }
    }//GEN-LAST:event_jt_CiudadKeyTyped

    private void jt_DireccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jt_DireccionKeyTyped
        int limite = 60;
        if (jt_Direccion.getText().length() >= limite){
            evt.consume();
        }
    }//GEN-LAST:event_jt_DireccionKeyTyped

    private void jt_TelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jt_TelefonoKeyTyped
        int limite = 20;
        if (jt_Telefono.getText().length() >= limite){
            evt.consume();
        }
        char caracter = evt.getKeyChar();
        if(((caracter < '0') || (caracter > '9')) && (caracter != '\b' /*corresponde a BACK_SPACE*/)) {
            evt.consume();  // ignorar el evento de teclado
        }
    }//GEN-LAST:event_jt_TelefonoKeyTyped

    private void jt_Correo_ElectronicoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jt_Correo_ElectronicoKeyTyped
        int limite = 60;
        if (jt_Correo_Electronico.getText().length() >= limite){
            evt.consume();
        }
    }//GEN-LAST:event_jt_Correo_ElectronicoKeyTyped

    private void jt_WebKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jt_WebKeyTyped
        int limite = 60;
        if (jt_Web.getText().length() >= limite){
            evt.consume();
        }
    }//GEN-LAST:event_jt_WebKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jb_Agregar;
    private javax.swing.JButton jb_Modificar;
    private javax.swing.JLabel jl_Ciudad;
    private javax.swing.JLabel jl_Correo_Electronico;
    private javax.swing.JLabel jl_Direccion;
    private javax.swing.JLabel jl_Icono;
    private javax.swing.JLabel jl_Pais;
    private javax.swing.JLabel jl_Telefono;
    private javax.swing.JLabel jl_Web;
    private javax.swing.JLabel jl_iNombre;
    private javax.swing.JLabel jl_idProveedor;
    private javax.swing.JTextField jt_Ciudad;
    private javax.swing.JTextField jt_Correo_Electronico;
    private javax.swing.JTextField jt_Direccion;
    private javax.swing.JTextField jt_Nombre;
    private javax.swing.JTextField jt_Pais;
    private javax.swing.JTextField jt_Telefono;
    private javax.swing.JTextField jt_Web;
    private javax.swing.JTextField jt_idProveedor;
    // End of variables declaration//GEN-END:variables
}
