/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import Conexion.Conexion;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DiegoAndrés
 */
public class JIF_Proveedor extends javax.swing.JInternalFrame {

    /**
     * Creates new form JIF_Proveedor
     */
    public JIF_Proveedor() {
        initComponents();
        llenarTablaProveedor();
        setTitle("PROVEEDOR");
    }

    private void llenarTablaProveedor() {
        DefaultTableModel dtm = (DefaultTableModel) jtb_Proveedores.getModel();
        while (dtm.getRowCount() > 0) {
            dtm.removeRow(0);
        }
        jtb_Proveedores.setModel(dtm);
        try {
            Conexion c = new Conexion();
            Statement s = c.c.createStatement();
            String sentence = "select idProveedor, nombre, pais, ciudad, direccion, telefono, correoElectronico, paginaWeb from tb_proveedor, tb_contacto where tb_contacto.`idUbicacion` = tb_proveedor.`contacto_idUbicacion`";
            ResultSet r = s.executeQuery(sentence);
            while (r.next()) {
                Object[] o = new Object[]{r.getString(1), r.getString(2), r.getString(3),
                    r.getString(4), r.getString(5), r.getString(6), r.getString(7), r.getString(8)};

                dtm.addRow(o);
                jtb_Proveedores.setModel(dtm);
            }
            c.c.close();
        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void rowToFields(int fila) {
        String idProveedor = jtb_Proveedores.getValueAt(fila, 0).toString();
        String nombre = jtb_Proveedores.getValueAt(fila, 1).toString();
        String pais = jtb_Proveedores.getValueAt(fila, 2).toString();
        String ciudad = jtb_Proveedores.getValueAt(fila, 3).toString();
        String direccion = jtb_Proveedores.getValueAt(fila, 4).toString();
        String tel = jtb_Proveedores.getValueAt(fila, 5).toString();
        String correo = jtb_Proveedores.getValueAt(fila, 6).toString();
        String web = jtb_Proveedores.getValueAt(fila, 7).toString();
        jt_idProveedor.setText(idProveedor);
        jt_Nombre.setText(nombre);
        jt_Pais.setText(pais);
        jt_Ciudad.setText(ciudad);
        jt_Direccion.setText(direccion);
        jt_Telefono.setText(tel);
        jt_Correo_Electronico.setText(correo);
        jt_Web.setText(web);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg_Find = new javax.swing.ButtonGroup();
        jl_iNombre = new javax.swing.JLabel();
        jl_Pais = new javax.swing.JLabel();
        jl_Ciudad = new javax.swing.JLabel();
        jl_Direccion = new javax.swing.JLabel();
        jl_Telefono = new javax.swing.JLabel();
        jl_Correo_Electronico = new javax.swing.JLabel();
        jl_Web = new javax.swing.JLabel();
        jt_Nombre = new javax.swing.JTextField();
        jt_Pais = new javax.swing.JTextField();
        jt_Ciudad = new javax.swing.JTextField();
        jt_Direccion = new javax.swing.JTextField();
        jt_Telefono = new javax.swing.JTextField();
        jt_Correo_Electronico = new javax.swing.JTextField();
        jt_Web = new javax.swing.JTextField();
        jb_Agregar = new javax.swing.JButton();
        jb_Modificar = new javax.swing.JButton();
        jl_idProveedor = new javax.swing.JLabel();
        jt_idProveedor = new javax.swing.JTextField();
        jl_Icono = new javax.swing.JLabel();
        jp_DatosGenerales = new javax.swing.JPanel();
        jb_Nuevo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtb_Proveedores = new javax.swing.JTable();
        jp_Contenedor = new javax.swing.JPanel();
        jrb_Cedula = new javax.swing.JRadioButton();
        jrb_Nombre = new javax.swing.JRadioButton();
        jt_Buscar = new javax.swing.JTextField();
        jb_Find = new javax.swing.JButton();
        jb_Limpiar = new javax.swing.JButton();
        jp_Find = new javax.swing.JPanel();
        jb_Borrar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("PROVEEDOR");
        setPreferredSize(new java.awt.Dimension(860, 680));
        setVisible(true);
        getContentPane().setLayout(null);

        jl_iNombre.setText("Nombre:");
        getContentPane().add(jl_iNombre);
        jl_iNombre.setBounds(50, 90, 92, 23);

        jl_Pais.setText("País:");
        getContentPane().add(jl_Pais);
        jl_Pais.setBounds(50, 120, 92, 23);

        jl_Ciudad.setText("Ciudad:");
        getContentPane().add(jl_Ciudad);
        jl_Ciudad.setBounds(50, 150, 92, 23);

        jl_Direccion.setText("Dirección:");
        getContentPane().add(jl_Direccion);
        jl_Direccion.setBounds(50, 180, 92, 23);

        jl_Telefono.setText("Teléfono:");
        getContentPane().add(jl_Telefono);
        jl_Telefono.setBounds(50, 210, 92, 23);

        jl_Correo_Electronico.setText("Correo Electrónico:");
        getContentPane().add(jl_Correo_Electronico);
        jl_Correo_Electronico.setBounds(50, 240, 110, 23);

        jl_Web.setText("Página Web:");
        getContentPane().add(jl_Web);
        jl_Web.setBounds(50, 270, 92, 23);

        jt_Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt_NombreActionPerformed(evt);
            }
        });
        jt_Nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jt_NombreKeyTyped(evt);
            }
        });
        getContentPane().add(jt_Nombre);
        jt_Nombre.setBounds(160, 90, 300, 25);

        jt_Pais.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jt_PaisKeyTyped(evt);
            }
        });
        getContentPane().add(jt_Pais);
        jt_Pais.setBounds(160, 120, 300, 25);

        jt_Ciudad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jt_CiudadKeyTyped(evt);
            }
        });
        getContentPane().add(jt_Ciudad);
        jt_Ciudad.setBounds(160, 150, 300, 25);

        jt_Direccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jt_DireccionKeyTyped(evt);
            }
        });
        getContentPane().add(jt_Direccion);
        jt_Direccion.setBounds(160, 180, 300, 25);

        jt_Telefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jt_TelefonoKeyTyped(evt);
            }
        });
        getContentPane().add(jt_Telefono);
        jt_Telefono.setBounds(160, 210, 300, 25);

        jt_Correo_Electronico.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jt_Correo_ElectronicoKeyTyped(evt);
            }
        });
        getContentPane().add(jt_Correo_Electronico);
        jt_Correo_Electronico.setBounds(160, 240, 300, 25);

        jt_Web.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jt_WebKeyTyped(evt);
            }
        });
        getContentPane().add(jt_Web);
        jt_Web.setBounds(160, 270, 300, 25);

        jb_Agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/img_agregar.png"))); // NOI18N
        jb_Agregar.setText("Agregar");
        jb_Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_AgregarActionPerformed(evt);
            }
        });
        getContentPane().add(jb_Agregar);
        jb_Agregar.setBounds(40, 320, 100, 30);

        jb_Modificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/img_modificar.png"))); // NOI18N
        jb_Modificar.setText("Modificar");
        jb_Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_ModificarActionPerformed(evt);
            }
        });
        getContentPane().add(jb_Modificar);
        jb_Modificar.setBounds(370, 320, 100, 30);

        jl_idProveedor.setText("Id. Proveedor:");
        getContentPane().add(jl_idProveedor);
        jl_idProveedor.setBounds(50, 60, 92, 23);

        jt_idProveedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jt_idProveedorKeyTyped(evt);
            }
        });
        getContentPane().add(jt_idProveedor);
        jt_idProveedor.setBounds(160, 60, 300, 25);

        jl_Icono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/img_supplies.png"))); // NOI18N
        getContentPane().add(jl_Icono);
        jl_Icono.setBounds(530, 0, 300, 280);

        jp_DatosGenerales.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Generales"));
        getContentPane().add(jp_DatosGenerales);
        jp_DatosGenerales.setBounds(30, 40, 450, 270);

        jb_Nuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/img_nuevo.png"))); // NOI18N
        jb_Nuevo.setText("Nuevo");
        jb_Nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_NuevoActionPerformed(evt);
            }
        });
        getContentPane().add(jb_Nuevo);
        jb_Nuevo.setBounds(150, 320, 100, 30);

        jtb_Proveedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NIT", "Nombre", "País", "Ciudad", "Dirección", "Teléfono", "Correo Electrónico", "Página Web"
            }
        ));
        jtb_Proveedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtb_ProveedoresMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtb_Proveedores);
        if (jtb_Proveedores.getColumnModel().getColumnCount() > 0) {
            jtb_Proveedores.getColumnModel().getColumn(0).setPreferredWidth(8);
            jtb_Proveedores.getColumnModel().getColumn(2).setPreferredWidth(8);
            jtb_Proveedores.getColumnModel().getColumn(3).setPreferredWidth(8);
            jtb_Proveedores.getColumnModel().getColumn(5).setPreferredWidth(8);
        }

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 430, 800, 200);

        jp_Contenedor.setBorder(javax.swing.BorderFactory.createTitledBorder("Proveedores Registrados"));
        getContentPane().add(jp_Contenedor);
        jp_Contenedor.setBounds(10, 410, 820, 230);

        bg_Find.add(jrb_Cedula);
        jrb_Cedula.setSelected(true);
        jrb_Cedula.setText("Cédula");
        jrb_Cedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb_CedulaActionPerformed(evt);
            }
        });
        getContentPane().add(jrb_Cedula);
        jrb_Cedula.setBounds(500, 330, 80, 30);

        bg_Find.add(jrb_Nombre);
        jrb_Nombre.setText("Nombre");
        jrb_Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb_NombreActionPerformed(evt);
            }
        });
        getContentPane().add(jrb_Nombre);
        jrb_Nombre.setBounds(500, 360, 80, 30);

        jt_Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt_BuscarActionPerformed(evt);
            }
        });
        jt_Buscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jt_BuscarKeyTyped(evt);
            }
        });
        getContentPane().add(jt_Buscar);
        jt_Buscar.setBounds(600, 330, 150, 30);

        jb_Find.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/img_buscar.png"))); // NOI18N
        jb_Find.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_FindActionPerformed(evt);
            }
        });
        getContentPane().add(jb_Find);
        jb_Find.setBounds(750, 330, 49, 30);

        jb_Limpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/img_clear.png"))); // NOI18N
        jb_Limpiar.setText("Limpiar");
        jb_Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_LimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(jb_Limpiar);
        jb_Limpiar.setBounds(600, 360, 200, 25);

        jp_Find.setBorder(javax.swing.BorderFactory.createTitledBorder("Herramientas de Búsqueda"));
        getContentPane().add(jp_Find);
        jp_Find.setBounds(490, 310, 330, 90);

        jb_Borrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/img_borrar.png"))); // NOI18N
        jb_Borrar.setText("Borrar");
        jb_Borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_BorrarActionPerformed(evt);
            }
        });
        getContentPane().add(jb_Borrar);
        jb_Borrar.setBounds(260, 320, 100, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_AgregarActionPerformed
        if (evt.getSource() == jb_Agregar) {
            String id = jt_idProveedor.getText();
            String nombre = jt_Nombre.getText();
            String pais = jt_Pais.getText();
            String ciudad = jt_Ciudad.getText();
            String direccion = jt_Direccion.getText();
            String telefono = jt_Telefono.getText();
            String correo = jt_Correo_Electronico.getText();
            String web = jt_Web.getText();

            Conexion c;
            ttry:
            try {
                c = new Conexion();
                try (Statement s = c.c.createStatement()) {
                    if (pais.equals("") || ciudad.equals("")) {
                        pais = "Colombia";
                        ciudad = "Bogotá";
                    }
                    if (telefono.length() == 0) {
                        telefono = "0";
                    }
                    if (jt_idProveedor.getText().length() == 0 || jt_Nombre.getText().length() == 0) {
                        JOptionPane.showMessageDialog(this, "Complete todos los campos.", "Error", JOptionPane.ERROR_MESSAGE);
                        break ttry;
                    }
                    int ntelefono = Integer.parseInt(telefono);
                    ResultSet repetido = s.executeQuery("SELECT idProveedor FROM tb_proveedor where idProveedor = " + id);
                    if (repetido.next()) {
                        String idRepetido = repetido.getString(1);
                        if (idRepetido.length() != 0) {
                            JOptionPane.showMessageDialog(this, "No se ha podido agregar. El proveedor ya existe.", "Error", JOptionPane.ERROR_MESSAGE);
                            break ttry;
                        }
                    }
                    s.executeUpdate("insert into tb_Contacto (nombre, pais, ciudad, direccion, telefono, correoElectronico) VALUES ('" + nombre + "','" + pais + "','" + ciudad + "','" + direccion + "'," + ntelefono + ",'" + correo + "')");
                    ResultSet r = s.executeQuery("SELECT MAX(idUbicacion) FROM tb_Contacto");
                    if (r.next()) {
                        String ubicacion = r.getString(1);
                        int nubicacion = Integer.parseInt(ubicacion);
                        s.executeUpdate("insert into tb_Proveedor (idProveedor, paginaWeb, contacto_idUbicacion) VALUES ('" + id + "','" + web + "'," + nubicacion + ")");
                    }
                    JOptionPane.showMessageDialog(null, "Proveedor Registrado Satisfactoriamente!");
                    jt_idProveedor.setText("");
                    jt_Nombre.setText("");
                    jt_Pais.setText("");
                    jt_Ciudad.setText("");
                    jt_Direccion.setText("");
                    jt_Telefono.setText("");
                    jt_Correo_Electronico.setText("");
                    jt_Web.setText("");
                    llenarTablaProveedor();
                    s.close();
                }

            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(JIF_Cliente.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jb_AgregarActionPerformed

    private void jt_NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt_NombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jt_NombreActionPerformed

    private void jb_ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_ModificarActionPerformed
        String id = jt_idProveedor.getText();
        String nombre = jt_Nombre.getText();
        String pais = jt_Pais.getText();
        String ciudad = jt_Ciudad.getText();
        String direccion = jt_Direccion.getText();
        String telefono = jt_Telefono.getText();
        String correo = jt_Correo_Electronico.getText();
        String web = jt_Web.getText();

        Conexion c;
        ttry:
        try {
            c = new Conexion();
            try (Statement s = c.c.createStatement()) {
                if (pais.equals("") || ciudad.equals("")) {
                    pais = "Colombia";
                    ciudad = "Bogotá";
                }
                if (telefono.length() == 0) {
                    telefono = "0";
                }
                if (jt_idProveedor.getText().length() == 0 || jt_Nombre.getText().length() == 0) {
                    JOptionPane.showMessageDialog(this, "Complete todos los campos.", "Error", JOptionPane.ERROR_MESSAGE);
                    break ttry;
                }
                int ntelefono = Integer.parseInt(telefono);
                s.executeUpdate("update tb_Contacto, tb_Proveedor set nombre = '" + nombre + "', pais = '" + pais + "', ciudad = '" + ciudad + "', direccion = '" + direccion + "', telefono = " + ntelefono + ", correoElectronico = '" + correo + "' , paginaWeb = '" + web + "' " + "where tb_Contacto.idUbicacion = tb_Proveedor.contacto_idUbicacion and idProveedor = " + id);
                JOptionPane.showMessageDialog(null, "Proveedor Modificado Satisfactoriamente!");
                jt_idProveedor.setText("");
                jt_Nombre.setText("");
                jt_Pais.setText("");
                jt_Ciudad.setText("");
                jt_Direccion.setText("");
                jt_Telefono.setText("");
                jt_Correo_Electronico.setText("");
                jt_Web.setText("");
                llenarTablaProveedor();
                s.close();
            }

        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(JIF_Cliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jb_ModificarActionPerformed

    private void jt_idProveedorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jt_idProveedorKeyTyped
        char caracter = evt.getKeyChar();
        if (((caracter < '0') || (caracter > '9')) && (caracter != '\b' /*corresponde a BACK_SPACE*/)) {
            evt.consume();  // ignorar el evento de teclado
        }
    }//GEN-LAST:event_jt_idProveedorKeyTyped

    private void jt_NombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jt_NombreKeyTyped
        int limite = 60;
        if (jt_Nombre.getText().length() >= limite) {
            evt.consume();
        }
        char caracter = evt.getKeyChar();
        if ((caracter < '0') || (caracter > '9')) {
        } else {
            evt.consume();
        }
    }//GEN-LAST:event_jt_NombreKeyTyped

    private void jt_PaisKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jt_PaisKeyTyped
        int limite = 20;
        if (jt_Pais.getText().length() >= limite) {
            evt.consume();
        }
        char caracter = evt.getKeyChar();
        if ((caracter < '0') || (caracter > '9')) {
        } else {
            evt.consume();
        }
    }//GEN-LAST:event_jt_PaisKeyTyped

    private void jt_CiudadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jt_CiudadKeyTyped
        int limite = 20;
        if (jt_Ciudad.getText().length() >= limite) {
            evt.consume();
        }
        char caracter = evt.getKeyChar();
        if ((caracter < '0') || (caracter > '9')) {
        } else {
            evt.consume();
        }
    }//GEN-LAST:event_jt_CiudadKeyTyped

    private void jt_DireccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jt_DireccionKeyTyped
        int limite = 60;
        if (jt_Direccion.getText().length() >= limite) {
            evt.consume();
        }
    }//GEN-LAST:event_jt_DireccionKeyTyped

    private void jt_TelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jt_TelefonoKeyTyped
        int limite = 20;
        if (jt_Telefono.getText().length() >= limite) {
            evt.consume();
        }
        char caracter = evt.getKeyChar();
        if (((caracter < '0') || (caracter > '9')) && (caracter != '\b' /*corresponde a BACK_SPACE*/)) {
            evt.consume();  // ignorar el evento de teclado
        }
    }//GEN-LAST:event_jt_TelefonoKeyTyped

    private void jt_Correo_ElectronicoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jt_Correo_ElectronicoKeyTyped
        int limite = 60;
        if (jt_Correo_Electronico.getText().length() >= limite) {
            evt.consume();
        }
    }//GEN-LAST:event_jt_Correo_ElectronicoKeyTyped

    private void jt_WebKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jt_WebKeyTyped
        int limite = 60;
        if (jt_Web.getText().length() >= limite) {
            evt.consume();
        }
    }//GEN-LAST:event_jt_WebKeyTyped

    private void jb_NuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_NuevoActionPerformed
        jt_idProveedor.setText("");
        jt_Nombre.setText("");
        jt_Pais.setText("");
        jt_Ciudad.setText("");
        jt_Direccion.setText("");
        jt_Telefono.setText("");
        jt_Correo_Electronico.setText("");
        jt_Web.setText("");
    }//GEN-LAST:event_jb_NuevoActionPerformed

    private void jrb_CedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb_CedulaActionPerformed
        jt_Buscar.setText("");
    }//GEN-LAST:event_jrb_CedulaActionPerformed

    private void jrb_NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb_NombreActionPerformed
        jt_Buscar.setText("");
    }//GEN-LAST:event_jrb_NombreActionPerformed

    private void jt_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt_BuscarActionPerformed

    }//GEN-LAST:event_jt_BuscarActionPerformed

    private void jt_BuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jt_BuscarKeyTyped
        if (jrb_Cedula.isSelected()) {
            char caracter = evt.getKeyChar();
            if (((caracter < '0') || (caracter > '9')) && (caracter != '\b' /*corresponde a BACK_SPACE*/)) {
                evt.consume();  // ignorar el evento de teclado
            }
        }
    }//GEN-LAST:event_jt_BuscarKeyTyped

    private void jb_FindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_FindActionPerformed
        Conexion c;
        DefaultTableModel dtm = (DefaultTableModel) jtb_Proveedores.getModel();
        while (dtm.getRowCount() > 0) {
            dtm.removeRow(0);
        }
        jtb_Proveedores.setModel(dtm);
        try {
            c = new Conexion();
            try (Statement s = c.c.createStatement()) {
                if (jrb_Cedula.isSelected()) {
                    String id = jt_Buscar.getText();
                    if (id.equals("")) {
                        id = "0";
                    }
                    int fId = Integer.parseInt(id);
                    String sentence = "select idProveedor, nombre, pais, ciudad, direccion, telefono, correoElectronico, paginaWeb from tb_proveedor, tb_contacto where tb_contacto.`idUbicacion` = tb_proveedor.`contacto_idUbicacion` and idProveedor = " + fId + "";
                    ResultSet r = s.executeQuery(sentence);
                    while (r.next()) {
                        Object[] o = new Object[]{r.getString(1), r.getString(2), r.getString(3),
                            r.getString(4), r.getString(5), r.getString(6), r.getString(7), r.getString(8)};

                        dtm.addRow(o);
                        jtb_Proveedores.setModel(dtm);
                    }
                } else if (jrb_Nombre.isSelected()) {
                    String nombre = jt_Buscar.getText();
                    String sentence = "select idProveedor, nombre, pais, ciudad, direccion, telefono, correoElectronico, paginaWeb from tb_proveedor, tb_contacto where tb_contacto.`idUbicacion` = tb_proveedor.`contacto_idUbicacion` and nombre like '%" + nombre + "%'";
                    ResultSet r = s.executeQuery(sentence);
                    while (r.next()) {
                        Object[] o = new Object[]{r.getString(1), r.getString(2), r.getString(3),
                            r.getString(4), r.getString(5), r.getString(6), r.getString(7), r.getString(8)};

                        dtm.addRow(o);
                        jtb_Proveedores.setModel(dtm);
                    }
                }
                s.close();
            }
        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jb_FindActionPerformed

    private void jb_LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_LimpiarActionPerformed
        jt_Buscar.setText("");
        llenarTablaProveedor();
    }//GEN-LAST:event_jb_LimpiarActionPerformed

    private void jtb_ProveedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtb_ProveedoresMouseClicked
        rowToFields(jtb_Proveedores.getSelectedRow());
    }//GEN-LAST:event_jtb_ProveedoresMouseClicked

    private void jb_BorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_BorrarActionPerformed
        String idProveedor = jt_idProveedor.getText();
        if (idProveedor.length() == 0) {
            JOptionPane.showMessageDialog(this, "Escriba el id. del proveedor, está vacío.", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            int op = JOptionPane.showConfirmDialog(this, "¿Está seguro que desea borrar el\nproveedor asociado al Id. " + idProveedor + " ?");
            if (op == JOptionPane.YES_OPTION) {
                try {
                    Conexion c = new Conexion();
                    Statement s = c.c.createStatement();
                    String sentence = "CALL sp_borrarProveedor(" + idProveedor + ")";
                    ResultSet r = s.executeQuery(sentence);
                    if (r.next()) {
                        String ans = r.getString(1);
                        JOptionPane.showMessageDialog(this, ans);
                    } else {
                        JOptionPane.showMessageDialog(this, "Error al intentar borrar", "Error", JOptionPane.ERROR_MESSAGE);
                    }
                    c.c.close();
                } catch (ClassNotFoundException | SQLException ex) {
                    JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                }
                llenarTablaProveedor();
                jt_idProveedor.setText("");
                jt_Nombre.setText("");
                jt_Pais.setText("");
                jt_Ciudad.setText("");
                jt_Direccion.setText("");
                jt_Telefono.setText("");
                jt_Correo_Electronico.setText("");
                jt_Web.setText("");
            }
        }
    }//GEN-LAST:event_jb_BorrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bg_Find;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jb_Agregar;
    private javax.swing.JButton jb_Borrar;
    private javax.swing.JButton jb_Find;
    private javax.swing.JButton jb_Limpiar;
    private javax.swing.JButton jb_Modificar;
    private javax.swing.JButton jb_Nuevo;
    private javax.swing.JLabel jl_Ciudad;
    private javax.swing.JLabel jl_Correo_Electronico;
    private javax.swing.JLabel jl_Direccion;
    private javax.swing.JLabel jl_Icono;
    private javax.swing.JLabel jl_Pais;
    private javax.swing.JLabel jl_Telefono;
    private javax.swing.JLabel jl_Web;
    private javax.swing.JLabel jl_iNombre;
    private javax.swing.JLabel jl_idProveedor;
    private javax.swing.JPanel jp_Contenedor;
    private javax.swing.JPanel jp_DatosGenerales;
    private javax.swing.JPanel jp_Find;
    private javax.swing.JRadioButton jrb_Cedula;
    private javax.swing.JRadioButton jrb_Nombre;
    private javax.swing.JTextField jt_Buscar;
    private javax.swing.JTextField jt_Ciudad;
    private javax.swing.JTextField jt_Correo_Electronico;
    private javax.swing.JTextField jt_Direccion;
    private javax.swing.JTextField jt_Nombre;
    private javax.swing.JTextField jt_Pais;
    private javax.swing.JTextField jt_Telefono;
    private javax.swing.JTextField jt_Web;
    private javax.swing.JTextField jt_idProveedor;
    private javax.swing.JTable jtb_Proveedores;
    // End of variables declaration//GEN-END:variables
}
